"use client";
import { useMemo, useState } from "react";
import { Calculator } from "lucide-react";
export default function LoanCalculator(){
 const [amount,setAmount]=useState(50000); const [rate,setRate]=useState(18); const [months,setMonths]=useState(12);
 const result=useMemo(()=>{const r=rate/1200;const emi=r===0?amount/months:amount*r*Math.pow(1+r,months)/(Math.pow(1+r,months)-1);return {emi,total:emi*months,interest:emi*months-amount}},[amount,rate,months]);
 const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Math.round(n));
 return <><section className="page-hero"><div className="container"><div className="eyebrow">Free planning tool</div><h1>Estimate your loan<br/>repayments.</h1><p>Adjust the amount, interest rate and repayment period to estimate your monthly EMI and total interest. This is an estimate, not a lender quote.</p></div></section><section className="content-section"><div className="calc-card"><div className="eyebrow"><Calculator size={14}/> EMI calculator</div><label className="field-label" htmlFor="amount">Loan amount <strong style={{float:"right"}}>{money(amount)}</strong></label><input id="amount" type="range" min="5000" max="1000000" step="5000" value={amount} onChange={e=>setAmount(Number(e.target.value))}/><div className="range-values"><span>₹5,000</span><span>₹10,00,000</span></div>
 <label className="field-label" htmlFor="rate">Annual interest rate <strong style={{float:"right"}}>{rate}%</strong></label><input id="rate" type="range" min="6" max="36" step="0.5" value={rate} onChange={e=>setRate(Number(e.target.value))}/><div className="range-values"><span>6%</span><span>36%</span></div>
 <label className="field-label" htmlFor="months">Repayment period <strong style={{float:"right"}}>{months} months</strong></label><input id="months" type="range" min="3" max="60" step="1" value={months} onChange={e=>setMonths(Number(e.target.value))}/><div className="range-values"><span>3 months</span><span>60 months</span></div>
 <div className="calc-result"><span>Estimated monthly EMI</span><strong>{money(result.emi)}</strong><div className="result-row"><span>Principal amount</span><strong>{money(amount)}</strong></div><div className="result-row"><span>Estimated total interest</span><strong>{money(result.interest)}</strong></div><div className="result-row"><span>Total repayment</span><strong>{money(result.total)}</strong></div></div>
 <p className="small-note">Calculation assumes a fixed annual rate and equal monthly payments. It excludes processing fees, taxes, insurance and other charges. Actual lender calculations may differ.</p></div><h2>Use this estimate wisely</h2><p>Compare the total repayment and all disclosed charges, not only the EMI. Review the Key Facts Statement and loan agreement before accepting any offer.</p></section></>}
